# Generated by Django 5.2.7 on 2025-10-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
